# Generated by Django 4.2.5 on 2023-09-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HabitatCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='specie',
        ),
        migrations.AddField(
            model_name='food',
            name='composition',
            field=models.TextField(default='tasty'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zoo.animalclass'),
        ),
        migrations.AddField(
            model_name='animal',
            name='habitat_countries',
            field=models.ManyToManyField(to='zoo.habitatcountry'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zoo.employeeposition'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.animalspecies'),
        ),
    ]
