# Generated by Django 4.2.5 on 2023-09-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_remove_employee_position_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
