# Generated by Django 4.2.5 on 2023-09-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zoo.employeeposition'),
        ),
    ]
