# Generated by Django 4.2.5 on 2023-09-19 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_foodconsumption_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodconsumption',
            name='user',
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
