# Generated by Django 4.2.5 on 2023-09-19 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0009_remove_foodconsumption_user_foodconsumption_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
