# Generated by Django 4.2.5 on 2023-09-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0010_animal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_class',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='species',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_class',
            field=models.ManyToManyField(to='zoo.animalclass'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ManyToManyField(to='zoo.animalspecies'),
        ),
    ]
