# Generated by Django 4.2.5 on 2023-09-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0011_remove_animal_animal_class_remove_animal_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_class',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='species',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zoo.animalclass'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zoo.animalspecies'),
        ),
    ]
