# Generated by Django 4.2.5 on 2023-09-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0012_remove_animal_animal_class_remove_animal_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='assigned_enclosure',
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_enclosure',
            field=models.ManyToManyField(to='zoo.enclosure'),
        ),
    ]
