# Generated by Django 4.2.5 on 2023-09-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0013_remove_employee_assigned_enclosure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodconsumption',
            old_name='user_id',
            new_name='user',
        ),
    ]
