# Generated by Django 4.2.5 on 2023-09-20 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0015_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2004, 6, 27, 0, 0)),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='media/unknown.png', upload_to='employees_photos/'),
        ),
    ]
