# Generated by Django 4.2.5 on 2023-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0016_customuser_birth_date_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='unknown.png', upload_to='employees_photos/'),
        ),
    ]
