# Generated by Django 4.2.5 on 2023-09-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0018_jobvacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
