# Generated by Django 4.2.5 on 2023-09-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0020_faq_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
