# Generated by Django 4.2.5 on 2023-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0022_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название купона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('expiration_date', models.DateField(verbose_name='Срок действия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coupons/', verbose_name='Изображение')),
            ],
        ),
    ]
